python train.py config/train_shakespeare_char.py \
--device=cpu \
--compile=False \
--eval_iters=50 \
--log_interval=100 \
--block_size=1024 \
--batch_size=12 \
--n_layer=4 \
--n_head=4 \
--n_embd=128 \
--max_iters=2000 \
--lr_decay_iters=2000 \
--dropout=0.0 \
--init_from=scratch 